{% set name = "moleculekit" %}
{% set version = "1.8.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moleculekit-{{ version }}.tar.gz
  sha256: e3c6880ad80c2771e49279cfe6e8ede1be3cbc31d45dfe79cf565f15d9116ea7

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy >=1.18.5
    - cython >=0.29.21
    - toml
    - versioneer ==0.28
    - pip
  run:
    - python
    - pandas >=1.1.2
    - networkx
    - tqdm
    - mmtf-python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - moleculekit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Acellera/moleculekit
  summary: A molecule reading/writing and manipulation package.
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
