{% set name = "moleculekit" %}
{% set version = "1.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moleculekit-{{ version }}.tar.gz
  sha256: 4d5cdf6afa9ef9ea59e950ab6835e06ec0ed51c7307628e8b139117b5a8bb65d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy >=1.18.5
    - cython >=0.29.21
    - toml
    - versioneer ==0.26
    - pip
  run:
    - python
    - scipy
    - pandas >=1.1.2
    - networkx
    - tqdm
    - mmtf-python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - moleculekit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Acellera/moleculekit
  summary: A molecule reading/writing and manipulation package.
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
